name: CI

# Kotrolowanie podczas pracy
on:
  # Triggery kiedy ma się wykonać ta akcja
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Ten workflow zawiera jeden job o nazwie unitest
  unitest:
    # Ustawienie maszyny na którym będą się odbywały testy
    runs-on: ubuntu-latest

    # Kolejne kroki zadania
    steps:
      # Ustwanie czego używa workflow
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-verision: '3.8'
      
      # Pobranie zależności
      - name: Install numpy and pytest
        run: |
          pip install numpy
          pip install pytest
          
      # Uruchomienie testów
      - name: Run tests
        run: pytest ./test_kod.py
