on:
  pull_request:
    branches:
      - test
    types:
      - closed
jobs:
  push-docker-image:
    if: github.event.pull_request.merged
    
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3

    - name: Functional Tests
      uses: ./github/workflows/lab7_api.yml

    - name: Login to Docker Hub and push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        cd ./Lab6
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t devops-app .
        docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest